# Generated by Django 5.0.4 on 2024-04-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contactenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Fathername', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=20)),
                ('State', models.CharField(max_length=50)),
            ],
        ),
    ]
