# Generated by Django 5.0.4 on 2024-04-18 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Country',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='Phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
