# Generated by Django 5.0.4 on 2024-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_member_country_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Bank_ac',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='Education',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
