# Generated by Django 5.0.4 on 2024-04-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_member_himalay_member_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='h',
            field=models.CharField(default='Date', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='m',
            field=models.CharField(default='day', max_length=50),
        ),
    ]
