# Generated by Django 5.0.4 on 2024-04-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_member_h_member_m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Phone',
            new_name='mobileno',
        ),
    ]
